export const LOGIN_INFORMATION = "LOGIN_INFORMATION";
export const SIGN_UP_INFORMATION = "SIGN_UP_INFORMATION";
export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";

export const GET_GLOBAL_POSTS = "GET_GLOBAL_POSTS";
export const GET_FRIENDS_POSTS = "GET_FRIENDS_POSTS";
export const ADD_COMMENT_BUTTON_CLICKED = "ADD_COMMENT_BUTTON_CLICKED";
export const CHANGE_CURRENT_POST = "CHANGE_CURRENT_POST";
export const CHANGE_ADD_BUTTON = "CHANGE_ADD_BUTTON";
