export const LOGIN_INFORMATION = "LOGIN_INFORMATION";
export const SIGN_UP_INFORMATION = "SIGN_UP_INFORMATION";
export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";

export const GET_GLOBAL_POSTS = "GET_GLOBAL_POSTS";
