export const LOGIN = "LOGIN";
export const SIGN_UP = "SIGN_UP";
export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";
export const USER_SIGNED_UP = "USER_SIGNED_UP";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_FRIENDS_POSTS = "GET_FRIENDS_POSTS";
export const GET_PROFILE_POSTS = "GET_PROFILE_POSTS";
export const CHANGE_CURRENT_FOCUSED_POST = "CHANGE_CURRENT_FOCUSED_POST";
export const COMMENT_SUBMITTED_TO_A_PROFILE = "COMMENT_SUBMITTED_TO_A_PROFILE";

export const GET_AND_STORE_A_PROFILE = "GET_AND_STORE_A_PROFILE";
export const GET_AND_STORE_MY_PROFILE = "GET_AND_STORE_MY_PROFILE";
export const GET_FRIEND_THUMBNAIL = "GET_FRIEND_THUMBNAIL";
export const CHECK_FOR_FRIEND = "CHECK_FOR_FRIENDS";
export const ADD_FRIEND = "ADD_FRIEND";
export const REVERSE_ADDED_FRIEND = "REVERSE_ADDED_FRIEND";
